Repository Malwarebytes/ghas-cli, pull requests merged in 2025-05, with the labels that each got.

#115 Update codeql-action to latest version
  .github/workflows/codeql-analysis.yml
  templates/codeql-analysis-default.yml
Labels: dependencies

#116 Support GHA in dependabot.yml
  .github/dependabot.yml
Labels: enhancement, dependencies

#117 Move to uv
  .github/dependabot.yml
  poetry.lock
  pyproject.toml
  uv.lock
Labels: enhancement, configuration error, dependencies

#120 improve build process
  pyproject.toml
Labels: documentation, dependencies
